/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.Biblioteca;
import com.biblioteca.Edicion;
import com.biblioteca.Ejemplar;
import com.biblioteca.Formato;
import com.biblioteca.Identificacion;
import com.biblioteca.Obra;
import com.biblioteca.TipoObra;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dalzo
 */
public class DarBajaPanel extends javax.swing.JFrame {

    ArrayList<Ejemplar> ejemplares = null;
    ArrayList<Ejemplar> ejemplaresDeBaja = null;
    
    /**
     * Creates new form DarBajaPanel
     */
    public DarBajaPanel() {
        //Test code
        Edicion edicion = new Edicion("FEditorial", "Argentina", 1, 2002, 10_000, 367, "Español", Formato.PAPEL, null);
        Edicion edicion1 = new Edicion("FEditorial", "Argentina", 2, 2008, 10_000, 367, "Español", Formato.PAPEL, null);
        Edicion edicion2 = new Edicion("FEditorial", "Argentina", 3, 20015, 10_100, 367, "Español", Formato.PAPEL, null);

        ArrayList<Edicion> ediciones = new ArrayList<>();
        ediciones.add(edicion);
        ediciones.add(edicion1);
        ediciones.add(edicion2);
        
        

        Obra obra = new Obra("Calculo 1", "Subtitulo", "Autor1", "Autor2", "Autor3", "Matematica", "Educacion", "9780313338", ediciones, TipoObra.DIARIO);
        ArrayList<Obra> obras = new ArrayList();
        obras.add(obra);
        for (Edicion edicions : ediciones) {
            edicions.setObra(obra);
        }
        Biblioteca.guardarEdiciones(ediciones);        
        Biblioteca.guardarObras(obras);
        
        LocalDate adquisicion = LocalDate.of(2019, 7, 22);
        Identificacion seUbica = new Identificacion(null, 1, 1, 1, 1, 1);

        Ejemplar ejemplar = new Ejemplar("Observaciones", "9780313338", adquisicion, "Internet", seUbica, obra);
        seUbica.setSeUbica(ejemplar);
        obra.añadirEjemplar(ejemplar);
        
        //Init code
        ejemplares = new ArrayList();
        ejemplaresDeBaja = new ArrayList();
        ejemplares.add(ejemplar);
        initComponents();
        mostrarEjemplares();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cartelMotivo = new javax.swing.JTextField();
        motivoBaja = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baja de ejemplar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 33, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("BAJA DE EJEMPLAR");
        tituloPanel.setFocusable(false);
        jPanel1.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 8, 16));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Codigo", "Adquisicion", "Ubicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(65, 75, 95));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 560, -1));

        cartelMotivo.setEditable(false);
        cartelMotivo.setBackground(new java.awt.Color(3, 33, 67));
        cartelMotivo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelMotivo.setForeground(new java.awt.Color(255, 255, 255));
        cartelMotivo.setText("Motivo de baja");
        cartelMotivo.setBorder(null);
        cartelMotivo.setFocusable(false);
        jPanel1.add(cartelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        motivoBaja.setBackground(new java.awt.Color(0, 8, 16));
        motivoBaja.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(motivoBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 250, -1));

        eliminarBtn.setBackground(new java.awt.Color(96, 106, 135));
        eliminarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("Eliminar");
        eliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 130, 30));

        volverBtn.setBackground(new java.awt.Color(96, 106, 135));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        darBajaEjemplar();
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.setVisible(false);
        new AdminPanel().setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void mostrarEjemplares(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[4];
        
        for (Ejemplar ejemplar : ejemplares) {
            row[0] = ejemplar.getObra().getTitulo();
            row[1] = ejemplar.getCodigoDeBarra();
            row[2] = ejemplar.getFechaAdquisicion().toString();
            row[3] = ejemplar.getSeUbica().toString();
        }
        model.addRow(row);
    }
    
    private void darBajaEjemplar(){
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Ninguna fila seleccionada", "Error", 2);
        }else{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
            Ejemplar ejemplar = ejemplares.get(jTable1.getSelectedRow());
            try {
                ejemplar.darDeBaja(motivoBaja.getText());
            } catch (Exception ex) {
                Logger.getLogger(DarBajaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            ejemplaresDeBaja.add(ejemplar);
            ejemplares.remove(jTable1.getSelectedRow());

            model.removeRow(jTable1.getSelectedRow());
            mostrarEjemplares();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarBajaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarBajaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarBajaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarBajaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DarBajaPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cartelMotivo;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField motivoBaja;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
