/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

/**
 *
 * @author dalzo
 */
public class FuncionarioPanel extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioPanel
     */
    public FuncionarioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unerLogo = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        tomarPrestamoButon = new javax.swing.JButton();
        RecibirPrestamoBoton = new javax.swing.JButton();
        listPrestamosBoton = new javax.swing.JButton();
        listEjemplaresBoton = new javax.swing.JButton();
        reservarBoton = new javax.swing.JButton();
        tituloPanel = new javax.swing.JLabel();
        logoFuncionario = new javax.swing.JLabel();
        listMultadosBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FuncionarioHome");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 33, 67));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unerLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        unerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GUI/source/unerLoginLogo.png"))); // NOI18N
        unerLogo.setFocusable(false);
        unerLogo.setPreferredSize(new java.awt.Dimension(391, 101));
        jPanel1.add(unerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 60));

        logoutButton.setBackground(new java.awt.Color(96, 106, 135));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 357, 100, -1));

        tomarPrestamoButon.setBackground(new java.awt.Color(96, 106, 135));
        tomarPrestamoButon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tomarPrestamoButon.setForeground(new java.awt.Color(255, 255, 255));
        tomarPrestamoButon.setText("Tomar prestamo");
        tomarPrestamoButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tomarPrestamoButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarPrestamoButonActionPerformed(evt);
            }
        });
        jPanel1.add(tomarPrestamoButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 40));

        RecibirPrestamoBoton.setBackground(new java.awt.Color(96, 106, 135));
        RecibirPrestamoBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RecibirPrestamoBoton.setForeground(new java.awt.Color(255, 255, 255));
        RecibirPrestamoBoton.setText("Recibir prestamo");
        RecibirPrestamoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RecibirPrestamoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 150, 40));

        listPrestamosBoton.setBackground(new java.awt.Color(96, 106, 135));
        listPrestamosBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listPrestamosBoton.setForeground(new java.awt.Color(255, 255, 255));
        listPrestamosBoton.setText("Lisatado prestamos");
        listPrestamosBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listPrestamosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrestamosBotonActionPerformed(evt);
            }
        });
        jPanel1.add(listPrestamosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 150, 40));

        listEjemplaresBoton.setBackground(new java.awt.Color(96, 106, 135));
        listEjemplaresBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listEjemplaresBoton.setForeground(new java.awt.Color(255, 255, 255));
        listEjemplaresBoton.setText("Listado ejemplares");
        listEjemplaresBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listEjemplaresBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEjemplaresBotonActionPerformed(evt);
            }
        });
        jPanel1.add(listEjemplaresBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, 40));

        reservarBoton.setBackground(new java.awt.Color(96, 106, 135));
        reservarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservarBoton.setForeground(new java.awt.Color(255, 255, 255));
        reservarBoton.setText("Reservar ejemplar");
        reservarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(reservarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 40));

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("PANEL DE FUNCIONARIO");
        tituloPanel.setFocusable(false);
        jPanel1.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        logoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GUI/source/funcionario-logo.png"))); // NOI18N
        logoFuncionario.setFocusable(false);
        jPanel1.add(logoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        listMultadosBoton.setBackground(new java.awt.Color(96, 106, 135));
        listMultadosBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listMultadosBoton.setForeground(new java.awt.Color(255, 255, 255));
        listMultadosBoton.setText("Lectores multados");
        listMultadosBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(listMultadosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPrestamosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrestamosBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPrestamosBotonActionPerformed

    private void listEjemplaresBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEjemplaresBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listEjemplaresBotonActionPerformed

    private void tomarPrestamoButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarPrestamoButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomarPrestamoButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RecibirPrestamoBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listEjemplaresBoton;
    private javax.swing.JButton listMultadosBoton;
    private javax.swing.JButton listPrestamosBoton;
    private javax.swing.JLabel logoFuncionario;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton reservarBoton;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JButton tomarPrestamoButon;
    private javax.swing.JLabel unerLogo;
    // End of variables declaration//GEN-END:variables
}
