/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.Biblioteca;
import com.biblioteca.Edicion;
import com.biblioteca.Ejemplar;
import com.biblioteca.Estudiante;
import com.biblioteca.Formato;
import com.biblioteca.Funcionario;
import com.biblioteca.Identificacion;
import com.biblioteca.Lector;
import com.biblioteca.Obra;
import com.biblioteca.TipoDni;
import com.biblioteca.TipoObra;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dalzo
 */
public class ListadoEjemplares extends javax.swing.JFrame {

    ArrayList<Funcionario> funcionarios = null;
    ArrayList<Ejemplar> ejemplaresDisponibles = null;
    ArrayList<Obra> obras = null;
    ArrayList<Edicion> ediciones = null;
    ArrayList<Ejemplar> ejemplaresDeBaja = null;
    ArrayList<Lector> lectores = null;
    ArrayList<Ejemplar> ejemplaresPrestados = null;
    ArrayList<Ejemplar> ejemplaresReservados = null;
    
    //Para demostracion
    ArrayList<Ejemplar> ejemplaresGral = null;
    
    
    /**
     * Creates new form ListadoEjemplares
     */
    public ListadoEjemplares() {
        funcionarios = Biblioteca.cargarFuncionarios();
        ediciones = Biblioteca.cargarEdiciones();
        obras = Biblioteca.cargarObras(ediciones);
        ejemplaresDisponibles = Biblioteca.cargarEjemplaresDisponibles(obras);
        ejemplaresDeBaja = Biblioteca.cargarEjemplaresDeBaja(obras);
        lectores = Biblioteca.cargarLectores();
        ejemplaresPrestados = new ArrayList(); //Problema de lectura del csv
        ejemplaresReservados = new ArrayList(); //Problema de lectura del csv
        initComponents();
        setup();
        mostrarEjemplares(ejemplaresGral);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        fReserva = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        areaTematica = new javax.swing.JTextField();
        cartelCodigo = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        filtrarReserva = new javax.swing.JButton();
        cartelCodigo1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 33, 67));
        setResizable(false);

        bg.setBackground(new java.awt.Color(3, 33, 67));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("LISTADO DE EJEMPLARES");
        tituloPanel.setFocusable(false);
        bg.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        fReserva.setBackground(new java.awt.Color(0, 8, 16));
        fReserva.setForeground(new java.awt.Color(255, 255, 255));
        fReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        bg.add(fReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 250, -1));

        jTable1.setBackground(new java.awt.Color(0, 8, 16));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", " Identificacion", "Codigo", "Area de Referencia", "Fecha Reserva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(65, 75, 95));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 840, 300));

        areaTematica.setBackground(new java.awt.Color(0, 8, 16));
        areaTematica.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(areaTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 250, -1));

        cartelCodigo.setEditable(false);
        cartelCodigo.setBackground(new java.awt.Color(3, 33, 67));
        cartelCodigo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        cartelCodigo.setText("Fecha Reserva");
        cartelCodigo.setBorder(null);
        cartelCodigo.setFocusable(false);
        bg.add(cartelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 110, 20));

        volverBtn.setBackground(new java.awt.Color(96, 106, 135));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 30));

        buscarBtn.setBackground(new java.awt.Color(96, 106, 135));
        buscarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setText("Buscar por area");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        bg.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 170, 30));

        filtrarReserva.setBackground(new java.awt.Color(96, 106, 135));
        filtrarReserva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filtrarReserva.setForeground(new java.awt.Color(255, 255, 255));
        filtrarReserva.setText("Filtrar por fecha reserva");
        filtrarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarReservaActionPerformed(evt);
            }
        });
        bg.add(filtrarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 170, 30));

        cartelCodigo1.setEditable(false);
        cartelCodigo1.setBackground(new java.awt.Color(3, 33, 67));
        cartelCodigo1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        cartelCodigo1.setText("Area Tematica");
        cartelCodigo1.setBorder(null);
        cartelCodigo1.setFocusable(false);
        bg.add(cartelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.setVisible(false);
        new FuncionarioPanel().setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        if(areaTematica.getText().isEmpty()){
            mostrarEjemplares(ejemplaresGral);
        }else{
            mostrarEjemplares(Biblioteca.ejemplaresDisponiblesSegunTematica(areaTematica.getText(), obras));
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void filtrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarReservaActionPerformed
        if(fReserva.getText().isEmpty()){
            mostrarEjemplares(ejemplaresGral);
        }else{
            String formattedDate = fReserva.getText();
            String splittedDate[] = formattedDate.split("/");

            LocalDate fechaReserva = LocalDate.of(
                        Integer.parseInt(splittedDate[2]),
                        Integer.parseInt(splittedDate[1]),
                        Integer.parseInt(splittedDate[0])
            );
            
            mostrarEjemplares(Biblioteca.obrasReservadasPorFecha(fechaReserva, ejemplaresGral));
        }
        fReserva.setText(null);
    }//GEN-LAST:event_filtrarReservaActionPerformed

    private void mostrarEjemplares(ArrayList<Ejemplar> ejemplares){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Ejemplar ejemplar : ejemplares) {
            Object[] row = new Object[5];
            row[0] = ejemplar.getObra().getTitulo();
            row[1] = ejemplar.getSeUbica();
            row[2] = ejemplar.getCodigoDeBarra();
            row[3] = ejemplar.getObra().getAreaTematica();
            if(ejemplar.getReserva() != null){
                row[4] = ejemplar.getReserva().getFecha();
            }
            model.addRow(row);
        }
    }
    
    
    //Demostracion cargando Objetos en Memoria
    public void setup() {
        LocalDate nacimiento = LocalDate.of(2002, 3, 04);
        Estudiante estudiante = new Estudiante("Jeremias", "Panozzo", "Masculino", nacimiento, "44441299", TipoDni.DNI_TARJETA,
                "jeremiaspanozzo@gmail.com", "3456025247", "Argentino", "Concejal Veiga 1881", 3200, "Concordia",
                "Argentina");
        
        Edicion edicion1 = new Edicion("Editorial", "Argentina", 0, 
        2008, 2, 890, "Español", Formato.PAPEL, null);
        ArrayList<Edicion> edicionesTemp = new ArrayList<>();
        ediciones.add(edicion1);

        Obra obra = new Obra("Titulo", "subtitulo", "autor01", "autor02", 
            "autor03", "Matematica", "Educativo", "9789700502748", edicionesTemp, TipoObra.LIBRO);
        edicion1.setObra(obra);
        obras.add(obra);

        Identificacion ubi = new Identificacion(null, 1, 1, 1, 1, 1);
        Ejemplar ejemplar1 = new Ejemplar("Observaciones", "9789700502748", 
                LocalDate.of(2008, 4, 21), "Donacion", ubi, obra);
        ubi.setSeUbica(ejemplar1);
        

        Identificacion ubi2 = new Identificacion(null, 1, 1, 1, 1, 2);
        Ejemplar ejemplar2 = new Ejemplar("Observaciones", "9789700502748", 
                LocalDate.of(2008, 4, 21), "Donacion", ubi2, obra);
        ubi2.setSeUbica(ejemplar2);

        ArrayList<Ejemplar> ejemplaresPorReservar = new ArrayList();
        
        ejemplaresPorReservar = new ArrayList<>();
        ejemplaresPorReservar.add(ejemplar1);
        ejemplaresPorReservar.add(ejemplar2);

        //Ejemplares Disponibles
        ejemplaresDisponibles.add(ejemplar1);
        ejemplaresDisponibles.add(ejemplar2);

        LocalDate fechaReserva = LocalDate.of(2022, 10, 28);
        Biblioteca.reservarEjemplares(estudiante, fechaReserva, ejemplaresPorReservar, ejemplaresDisponibles,
        ejemplaresReservados);
        
        ejemplaresGral = new ArrayList();
        for (Ejemplar ejemplar : ejemplaresDisponibles) {
            ejemplaresGral.add(ejemplar);
        }
        for (Ejemplar ejemplar : ejemplaresReservados) {
            ejemplaresGral.add(ejemplar);
        }
        

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoEjemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoEjemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoEjemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoEjemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoEjemplares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaTematica;
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField cartelCodigo;
    private javax.swing.JTextField cartelCodigo1;
    private javax.swing.JFormattedTextField fReserva;
    private javax.swing.JButton filtrarReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
