/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.Biblioteca;
import com.biblioteca.Edicion;
import com.biblioteca.Ejemplar;
import com.biblioteca.Funcionario;
import com.biblioteca.Obra;
import com.biblioteca.TipoDni;
import com.biblioteca.TipoFuncionario;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dalzo
 */
public class Login extends javax.swing.JFrame {
    
    ArrayList<Funcionario> funcionarios = null;
    ArrayList<Ejemplar> ejemplaresDisponibles = null;
    ArrayList<Obra> obras = null;
    ArrayList<Edicion> ediciones = null;
    

    /**
     * Creates new form Login
     */
    public Login() {
        //Codigo con proposito de prueba:
        funcionarios = new ArrayList();
        funcionarios.add(new Funcionario("Jorge", "Hernandez", "Masculino", LocalDate.of(
                2001, 2, 23), "14798365", TipoDni.DNI_TARJETA,"admin",
                "admin", TipoFuncionario.ADMIN));
        //Codigo que no es de prueba
        initComponents();
    }
    
    public Login(ArrayList<Funcionario> funcionarioList, ArrayList<Ejemplar> ejemplaresList, ArrayList<Obra> obrasList, ArrayList<Edicion> edicionesList){
        funcionarios = funcionarioList;
        ejemplaresDisponibles = ejemplaresList;
        obras = obrasList;
        ediciones = edicionesList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        userBox = new javax.swing.JTextField();
        unerLogo = new javax.swing.JLabel();
        pwText = new javax.swing.JTextField();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        LoginButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        bg.setBackground(new java.awt.Color(3, 33, 67));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userBox.setBackground(new java.awt.Color(3, 33, 67));
        userBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userBox.setForeground(new java.awt.Color(255, 255, 255));
        userBox.setBorder(null);
        userBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBoxActionPerformed(evt);
            }
        });
        bg.add(userBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 20));

        unerLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        unerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GUI/source/unerLoginLogo.png"))); // NOI18N
        unerLogo.setPreferredSize(new java.awt.Dimension(391, 101));
        bg.add(unerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        pwText.setEditable(false);
        pwText.setBackground(new java.awt.Color(3, 33, 67));
        pwText.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        pwText.setForeground(new java.awt.Color(255, 255, 255));
        pwText.setText("Contraseña");
        pwText.setBorder(null);
        pwText.setFocusable(false);
        pwText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwTextActionPerformed(evt);
            }
        });
        bg.add(pwText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        userTxt.setEditable(false);
        userTxt.setBackground(new java.awt.Color(3, 33, 67));
        userTxt.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 255, 255));
        userTxt.setText("Usuario");
        userTxt.setBorder(null);
        userTxt.setFocusable(false);
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        bg.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 350, 10));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 350, 10));

        LoginButton.setBackground(new java.awt.Color(96, 106, 135));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Iniciar Sesion");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        bg.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(3, 33, 67));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 350, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GUI/source/icons8-cloud-library-64.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwTextActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        Logear();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void userBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBoxActionPerformed
        Logear();
    }//GEN-LAST:event_userBoxActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        Logear();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private Funcionario checkLogin(){
        String user = userBox.getText();
        String pw = String.valueOf(jPasswordField1.getPassword());
        
        
        for (Funcionario funcionario : funcionarios) {
            if(user.equals(funcionario.getUsuario()) && pw.equals(funcionario.getContrasenia())){
                return funcionario;
            }
        }
        return null;
    }
    
    private void Logear(){
        Funcionario funcionario = checkLogin();
        if (funcionario != null){
            this.setVisible(false);
            if (funcionario.getTipoFuncionario().equals(TipoFuncionario.ADMIN)){
                new AdminPanel(funcionarios,ejemplaresDisponibles,obras,ediciones).setVisible(true);
            }else{
                new FuncionarioPanel().setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Credenciales incorrectas");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField pwText;
    private javax.swing.JLabel unerLogo;
    private javax.swing.JTextField userBox;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
