/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.TipoDni;

/**
 *
 * @author dalzo
 */
public class NuevoFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroFuncionario
     */
    public NuevoFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        userTxt = new javax.swing.JTextField();
        userTxt1 = new javax.swing.JTextField();
        userTxt2 = new javax.swing.JTextField();
        userTxt3 = new javax.swing.JTextField();
        userTxt4 = new javax.swing.JTextField();
        userTxt5 = new javax.swing.JTextField();
        userTxt6 = new javax.swing.JTextField();
        userTxt7 = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Funcionario");
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        bg.setBackground(new java.awt.Color(3, 33, 67));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(0, 8, 16));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, -1));

        jTextField3.setBackground(new java.awt.Color(0, 8, 16));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, -1));

        jTextField4.setBackground(new java.awt.Color(0, 8, 16));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        jTextField5.setBackground(new java.awt.Color(0, 8, 16));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 170, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 8, 16));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));

        jFormattedTextField1.setBackground(new java.awt.Color(0, 8, 16));
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setText("aaaa/mm/dd");
        bg.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 170, -1));

        userTxt.setEditable(false);
        userTxt.setBackground(new java.awt.Color(3, 33, 67));
        userTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 255, 255));
        userTxt.setText("Nombre");
        userTxt.setBorder(null);
        userTxt.setFocusable(false);
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        bg.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        userTxt1.setEditable(false);
        userTxt1.setBackground(new java.awt.Color(3, 33, 67));
        userTxt1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt1.setForeground(new java.awt.Color(255, 255, 255));
        userTxt1.setText("Apellido");
        userTxt1.setBorder(null);
        userTxt1.setFocusable(false);
        userTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt1ActionPerformed(evt);
            }
        });
        bg.add(userTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        userTxt2.setEditable(false);
        userTxt2.setBackground(new java.awt.Color(3, 33, 67));
        userTxt2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt2.setForeground(new java.awt.Color(255, 255, 255));
        userTxt2.setText("Sexo");
        userTxt2.setBorder(null);
        userTxt2.setFocusable(false);
        userTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt2ActionPerformed(evt);
            }
        });
        bg.add(userTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        userTxt3.setEditable(false);
        userTxt3.setBackground(new java.awt.Color(3, 33, 67));
        userTxt3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt3.setForeground(new java.awt.Color(255, 255, 255));
        userTxt3.setText("Nacimiento");
        userTxt3.setBorder(null);
        userTxt3.setFocusable(false);
        userTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt3ActionPerformed(evt);
            }
        });
        bg.add(userTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        userTxt4.setEditable(false);
        userTxt4.setBackground(new java.awt.Color(3, 33, 67));
        userTxt4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt4.setForeground(new java.awt.Color(255, 255, 255));
        userTxt4.setText("DNI");
        userTxt4.setBorder(null);
        userTxt4.setFocusable(false);
        userTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt4ActionPerformed(evt);
            }
        });
        bg.add(userTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, -1));

        userTxt5.setEditable(false);
        userTxt5.setBackground(new java.awt.Color(3, 33, 67));
        userTxt5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt5.setForeground(new java.awt.Color(255, 255, 255));
        userTxt5.setText("Tipo DNI");
        userTxt5.setBorder(null);
        userTxt5.setFocusable(false);
        userTxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt5ActionPerformed(evt);
            }
        });
        bg.add(userTxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        userTxt6.setEditable(false);
        userTxt6.setBackground(new java.awt.Color(3, 33, 67));
        userTxt6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt6.setForeground(new java.awt.Color(255, 255, 255));
        userTxt6.setText("Usuario");
        userTxt6.setBorder(null);
        userTxt6.setFocusable(false);
        userTxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt6ActionPerformed(evt);
            }
        });
        bg.add(userTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, -1));

        userTxt7.setEditable(false);
        userTxt7.setBackground(new java.awt.Color(3, 33, 67));
        userTxt7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        userTxt7.setForeground(new java.awt.Color(255, 255, 255));
        userTxt7.setText("Contraseña");
        userTxt7.setBorder(null);
        userTxt7.setFocusable(false);
        userTxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt7ActionPerformed(evt);
            }
        });
        bg.add(userTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        logoutButton.setBackground(new java.awt.Color(96, 106, 135));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Crear funcionario");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, 30));

        jPasswordField1.setBackground(new java.awt.Color(0, 8, 16));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("jPasswordField1");
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 170, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 8, 16));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(TipoDni.values()));
        bg.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt1ActionPerformed

    private void userTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt2ActionPerformed

    private void userTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt3ActionPerformed

    private void userTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt4ActionPerformed

    private void userTxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt5ActionPerformed

    private void userTxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt6ActionPerformed

    private void userTxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<TipoDni> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField userTxt;
    private javax.swing.JTextField userTxt1;
    private javax.swing.JTextField userTxt2;
    private javax.swing.JTextField userTxt3;
    private javax.swing.JTextField userTxt4;
    private javax.swing.JTextField userTxt5;
    private javax.swing.JTextField userTxt6;
    private javax.swing.JTextField userTxt7;
    // End of variables declaration//GEN-END:variables
}
