/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.Coleccion;
import com.biblioteca.Edicion;
import com.biblioteca.Formato;
import com.biblioteca.Obra;
import com.biblioteca.TipoObra;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dalzo
 */
public class NuevaObra extends javax.swing.JFrame {

    ArrayList<Obra> obras = null;
    DefaultListModel<Edicion> listModel;
            
    /**
     * Creates new form NuevaObra
     */
    public NuevaObra() {
        initComponents();
        this.listModel = (DefaultListModel<Edicion>) this.jListEdiciones.getModel();
        obras = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        cartelTitulo = new javax.swing.JTextField();
        cartelIndice = new javax.swing.JTextField();
        cartelSubt = new javax.swing.JTextField();
        cartelpAutor = new javax.swing.JTextField();
        cartelsAutor = new javax.swing.JTextField();
        carteltAutor = new javax.swing.JTextField();
        cartelATematica = new javax.swing.JTextField();
        cartelGenero = new javax.swing.JTextField();
        cartelISBN = new javax.swing.JTextField();
        cartelTipoObra = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        pAutor = new javax.swing.JTextField();
        sAutor = new javax.swing.JTextField();
        tAutor = new javax.swing.JTextField();
        aTematica = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        indice = new javax.swing.JTextField();
        subtitulo = new javax.swing.JTextField();
        TipoObras = new javax.swing.JComboBox<>();
        guardarObraBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        checkColec = new javax.swing.JCheckBox();
        cartelEsColec = new javax.swing.JTextField();
        cartelNombre = new javax.swing.JTextField();
        nombreColeccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tituloPanel1 = new javax.swing.JLabel();
        guardarEdicionBtn = new javax.swing.JButton();
        cartelFormato = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        cartelEditorial = new javax.swing.JTextField();
        cartelPais = new javax.swing.JTextField();
        cartelAnio = new javax.swing.JTextField();
        cartelVol = new javax.swing.JTextField();
        editorial = new javax.swing.JTextField();
        volumenes = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        idioma = new javax.swing.JTextField();
        pags = new javax.swing.JTextField();
        cartelPags = new javax.swing.JTextField();
        cartelIdioma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEdiciones = new javax.swing.JList<>();
        formato = new javax.swing.JComboBox<>();
        cartelIsbnColeccion = new javax.swing.JTextField();
        isbnColeccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(3, 33, 67));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("Nueva Obra");
        tituloPanel.setFocusable(false);
        bg.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        cartelTitulo.setEditable(false);
        cartelTitulo.setBackground(new java.awt.Color(3, 33, 67));
        cartelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        cartelTitulo.setText("Titulo");
        cartelTitulo.setBorder(null);
        cartelTitulo.setFocusable(false);
        bg.add(cartelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        cartelIndice.setEditable(false);
        cartelIndice.setBackground(new java.awt.Color(3, 33, 67));
        cartelIndice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelIndice.setForeground(new java.awt.Color(255, 255, 255));
        cartelIndice.setText("Indice");
        cartelIndice.setBorder(null);
        cartelIndice.setFocusable(false);
        bg.add(cartelIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 50, -1));

        cartelSubt.setEditable(false);
        cartelSubt.setBackground(new java.awt.Color(3, 33, 67));
        cartelSubt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelSubt.setForeground(new java.awt.Color(255, 255, 255));
        cartelSubt.setText("Subtitulo");
        cartelSubt.setBorder(null);
        cartelSubt.setFocusable(false);
        bg.add(cartelSubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        cartelpAutor.setEditable(false);
        cartelpAutor.setBackground(new java.awt.Color(3, 33, 67));
        cartelpAutor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelpAutor.setForeground(new java.awt.Color(255, 255, 255));
        cartelpAutor.setText("Primer autor");
        cartelpAutor.setBorder(null);
        cartelpAutor.setFocusable(false);
        bg.add(cartelpAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        cartelsAutor.setEditable(false);
        cartelsAutor.setBackground(new java.awt.Color(3, 33, 67));
        cartelsAutor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelsAutor.setForeground(new java.awt.Color(255, 255, 255));
        cartelsAutor.setText("Segundo autor");
        cartelsAutor.setBorder(null);
        cartelsAutor.setFocusable(false);
        bg.add(cartelsAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        carteltAutor.setEditable(false);
        carteltAutor.setBackground(new java.awt.Color(3, 33, 67));
        carteltAutor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        carteltAutor.setForeground(new java.awt.Color(255, 255, 255));
        carteltAutor.setText("Tercer autor");
        carteltAutor.setBorder(null);
        carteltAutor.setFocusable(false);
        bg.add(carteltAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        cartelATematica.setEditable(false);
        cartelATematica.setBackground(new java.awt.Color(3, 33, 67));
        cartelATematica.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelATematica.setForeground(new java.awt.Color(255, 255, 255));
        cartelATematica.setText("Area tematica");
        cartelATematica.setBorder(null);
        cartelATematica.setFocusable(false);
        bg.add(cartelATematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, -1));

        cartelGenero.setEditable(false);
        cartelGenero.setBackground(new java.awt.Color(3, 33, 67));
        cartelGenero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelGenero.setForeground(new java.awt.Color(255, 255, 255));
        cartelGenero.setText("Genero");
        cartelGenero.setBorder(null);
        cartelGenero.setFocusable(false);
        bg.add(cartelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, -1));

        cartelISBN.setEditable(false);
        cartelISBN.setBackground(new java.awt.Color(3, 33, 67));
        cartelISBN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelISBN.setForeground(new java.awt.Color(255, 255, 255));
        cartelISBN.setText("ISBN");
        cartelISBN.setBorder(null);
        cartelISBN.setFocusable(false);
        bg.add(cartelISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, -1));

        cartelTipoObra.setEditable(false);
        cartelTipoObra.setBackground(new java.awt.Color(3, 33, 67));
        cartelTipoObra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelTipoObra.setForeground(new java.awt.Color(255, 255, 255));
        cartelTipoObra.setText("Tipo de Obra");
        cartelTipoObra.setBorder(null);
        cartelTipoObra.setFocusable(false);
        bg.add(cartelTipoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, -1));

        titulo.setBackground(new java.awt.Color(0, 8, 16));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, -1));

        pAutor.setBackground(new java.awt.Color(0, 8, 16));
        pAutor.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(pAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        sAutor.setBackground(new java.awt.Color(0, 8, 16));
        sAutor.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(sAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        tAutor.setBackground(new java.awt.Color(0, 8, 16));
        tAutor.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(tAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        aTematica.setBackground(new java.awt.Color(0, 8, 16));
        aTematica.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(aTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        genero.setBackground(new java.awt.Color(0, 8, 16));
        genero.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        isbn.setBackground(new java.awt.Color(0, 8, 16));
        isbn.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 250, -1));

        indice.setBackground(new java.awt.Color(0, 8, 16));
        indice.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(indice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 250, -1));

        subtitulo.setBackground(new java.awt.Color(0, 8, 16));
        subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, -1));

        TipoObras.setBackground(new java.awt.Color(0, 8, 16));
        TipoObras.setForeground(new java.awt.Color(255, 255, 255));
        TipoObras.setModel(new javax.swing.DefaultComboBoxModel<>(TipoObra.values()));
        bg.add(TipoObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, -1));

        guardarObraBtn.setBackground(new java.awt.Color(96, 106, 135));
        guardarObraBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarObraBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarObraBtn.setText("Guardar Obra");
        guardarObraBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarObraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarObraBtnActionPerformed(evt);
            }
        });
        bg.add(guardarObraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 130, 30));

        volverBtn.setBackground(new java.awt.Color(96, 106, 135));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 130, 30));

        checkColec.setBackground(new java.awt.Color(3, 33, 67));
        checkColec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkColecStateChanged(evt);
            }
        });
        bg.add(checkColec, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 20, 20));

        cartelEsColec.setEditable(false);
        cartelEsColec.setBackground(new java.awt.Color(3, 33, 67));
        cartelEsColec.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelEsColec.setForeground(new java.awt.Color(255, 255, 255));
        cartelEsColec.setText("Es coleccion");
        cartelEsColec.setBorder(null);
        cartelEsColec.setFocusable(false);
        bg.add(cartelEsColec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, -1));

        cartelNombre.setEditable(false);
        cartelNombre.setBackground(new java.awt.Color(3, 33, 67));
        cartelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelNombre.setForeground(new java.awt.Color(187, 187, 255));
        cartelNombre.setText("Nombre");
        cartelNombre.setBorder(null);
        cartelNombre.setFocusable(false);
        bg.add(cartelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        nombreColeccion.setEditable(false);
        nombreColeccion.setBackground(new java.awt.Color(0, 8, 16));
        nombreColeccion.setForeground(new java.awt.Color(255, 255, 255));
        nombreColeccion.setFocusable(false);
        bg.add(nombreColeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 180, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 3, 10, 500));

        tituloPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel1.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel1.setText("Ediciones");
        tituloPanel1.setFocusable(false);
        bg.add(tituloPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 110, -1));

        guardarEdicionBtn.setBackground(new java.awt.Color(96, 106, 135));
        guardarEdicionBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarEdicionBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarEdicionBtn.setText("Agregar edicion");
        guardarEdicionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarEdicionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEdicionBtnActionPerformed(evt);
            }
        });
        bg.add(guardarEdicionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 130, 30));

        cartelFormato.setEditable(false);
        cartelFormato.setBackground(new java.awt.Color(3, 33, 67));
        cartelFormato.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelFormato.setForeground(new java.awt.Color(255, 255, 255));
        cartelFormato.setText("Formato");
        cartelFormato.setBorder(null);
        cartelFormato.setFocusable(false);
        bg.add(cartelFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 70, -1));

        pais.setBackground(new java.awt.Color(0, 8, 16));
        pais.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 220, 20));

        cartelEditorial.setEditable(false);
        cartelEditorial.setBackground(new java.awt.Color(3, 33, 67));
        cartelEditorial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelEditorial.setForeground(new java.awt.Color(255, 255, 255));
        cartelEditorial.setText("Editorial");
        cartelEditorial.setBorder(null);
        cartelEditorial.setFocusable(false);
        bg.add(cartelEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 70, -1));

        cartelPais.setEditable(false);
        cartelPais.setBackground(new java.awt.Color(3, 33, 67));
        cartelPais.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelPais.setForeground(new java.awt.Color(255, 255, 255));
        cartelPais.setText("Pais");
        cartelPais.setBorder(null);
        cartelPais.setFocusable(false);
        bg.add(cartelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 50, -1));

        cartelAnio.setEditable(false);
        cartelAnio.setBackground(new java.awt.Color(3, 33, 67));
        cartelAnio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelAnio.setForeground(new java.awt.Color(255, 255, 255));
        cartelAnio.setText("Año");
        cartelAnio.setBorder(null);
        cartelAnio.setFocusable(false);
        bg.add(cartelAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 50, -1));

        cartelVol.setEditable(false);
        cartelVol.setBackground(new java.awt.Color(3, 33, 67));
        cartelVol.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelVol.setForeground(new java.awt.Color(255, 255, 255));
        cartelVol.setText("Volumenes");
        cartelVol.setBorder(null);
        cartelVol.setFocusable(false);
        bg.add(cartelVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 80, -1));

        editorial.setBackground(new java.awt.Color(0, 8, 16));
        editorial.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 220, 20));

        volumenes.setBackground(new java.awt.Color(0, 8, 16));
        volumenes.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(volumenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 220, 20));

        anio.setBackground(new java.awt.Color(0, 8, 16));
        anio.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 220, 20));

        idioma.setBackground(new java.awt.Color(0, 8, 16));
        idioma.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 220, 20));

        pags.setBackground(new java.awt.Color(0, 8, 16));
        pags.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(pags, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 220, 20));

        cartelPags.setEditable(false);
        cartelPags.setBackground(new java.awt.Color(3, 33, 67));
        cartelPags.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelPags.setForeground(new java.awt.Color(255, 255, 255));
        cartelPags.setText("Paginas");
        cartelPags.setBorder(null);
        cartelPags.setFocusable(false);
        bg.add(cartelPags, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, -1));

        cartelIdioma.setEditable(false);
        cartelIdioma.setBackground(new java.awt.Color(3, 33, 67));
        cartelIdioma.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelIdioma.setForeground(new java.awt.Color(255, 255, 255));
        cartelIdioma.setText("Idioma");
        cartelIdioma.setBorder(null);
        cartelIdioma.setFocusable(false);
        bg.add(cartelIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 60, -1));

        jListEdiciones.setBackground(new java.awt.Color(0, 8, 16));
        jListEdiciones.setForeground(new java.awt.Color(255, 255, 255));
        jListEdiciones.setModel(new DefaultListModel<Edicion>());
        jScrollPane1.setViewportView(jListEdiciones);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 326, 290, 120));

        formato.setBackground(new java.awt.Color(0, 8, 16));
        formato.setForeground(new java.awt.Color(255, 255, 255));
        formato.setModel(new javax.swing.DefaultComboBoxModel<>(Formato.values()));
        bg.add(formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 220, -1));

        cartelIsbnColeccion.setEditable(false);
        cartelIsbnColeccion.setBackground(new java.awt.Color(3, 33, 67));
        cartelIsbnColeccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelIsbnColeccion.setForeground(new java.awt.Color(187, 187, 255));
        cartelIsbnColeccion.setText("ISBN");
        cartelIsbnColeccion.setBorder(null);
        cartelIsbnColeccion.setFocusable(false);
        bg.add(cartelIsbnColeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, 20));

        isbnColeccion.setEditable(false);
        isbnColeccion.setBackground(new java.awt.Color(0, 8, 16));
        isbnColeccion.setForeground(new java.awt.Color(255, 255, 255));
        isbnColeccion.setFocusable(false);
        bg.add(isbnColeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.setVisible(false);
        new DarAltaPanel().setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void checkColecStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkColecStateChanged
        if(checkColec.isSelected()){
            cartelNombre.setForeground(new java.awt.Color(255, 255, 255));
            nombreColeccion.setFocusable(true);
            nombreColeccion.setEditable(true);
            cartelIsbnColeccion.setForeground(new java.awt.Color(255, 255, 255));
            isbnColeccion.setFocusable(true);
            isbnColeccion.setEditable(true);
        }else{
            cartelNombre.setForeground(new java.awt.Color(187, 187, 255));
            nombreColeccion.setEditable(false);
            nombreColeccion.setFocusable(false);
            nombreColeccion.setText(null);
            cartelIsbnColeccion.setForeground(new java.awt.Color(187, 187, 255));
            isbnColeccion.setFocusable(false);
            isbnColeccion.setEditable(false);
        }
    }//GEN-LAST:event_checkColecStateChanged

    private void guardarEdicionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEdicionBtnActionPerformed
        listModel.addElement(new Edicion("editorial", "pais", 1, 2001, 2, 200, "español", Formato.CD, null));
    }//GEN-LAST:event_guardarEdicionBtnActionPerformed

    private void guardarObraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarObraBtnActionPerformed
        if(checkNoNulls()){
            try{
                crearObra();
                setAllToNull();
                JOptionPane.showMessageDialog(rootPane, "Obra creada exitosamente!", "Aviso", 1);
            }catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", 2);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Faltan completar campos", "Error", 2);
        }
    }//GEN-LAST:event_guardarObraBtnActionPerformed
    
    private void crearObra() throws IllegalArgumentException{
        //Union en ArrayList de las ediciones creadas
        ArrayList<Edicion> ediciones = new ArrayList();
        
        for (int i = 0; i < listModel.size(); i++) {
            Edicion edicion = listModel.getElementAt(i);
            ediciones.add(edicion);
        }
        
        //creacion de Obra o Coleccion
        if(checkColec.isSelected()){
            //creacion de la coleccion
            Coleccion coleccion = new Coleccion(
                    titulo.getText(),
                    subtitulo.getText(),
                    pAutor.getText(),
                    sAutor.getText(),
                    tAutor.getText(),
                    aTematica.getText(),
                    genero.getText(),
                    isbn.getText(),
                    ediciones,
                    nombreColeccion.getText(),
                    isbnColeccion.getText()
            );
            obras.add(coleccion);
            
        }else{
            //creacion de la obra
            Obra obra = new Obra(
                    titulo.getText(),
                    subtitulo.getText(),
                    pAutor.getText(),
                    sAutor.getText(),
                    tAutor.getText(),
                    aTematica.getText(),
                    genero.getText(),
                    isbn.getText(),
                    ediciones
            );

            obras.add(obra);
        }
    }
    
    private boolean checkNoNulls(){
        if(checkColec.isSelected()){
            return !(
                    titulo.getText().isEmpty()
                    || subtitulo.getText().isEmpty()
                    || pAutor.getText().isEmpty()
                    || sAutor.getText().isEmpty()
                    || tAutor.getText().isEmpty()
                    || aTematica.getText().isEmpty()
                    || genero.getText().isEmpty()
                    || isbn.getText().isEmpty()
                    || listModel.size() <= 0
                    || nombreColeccion.getText().isEmpty()
                    || isbnColeccion.getText().isEmpty()
                );
        }
        return !(
                    titulo.getText().isEmpty()
                    || subtitulo.getText().isEmpty()
                    || pAutor.getText().isEmpty()
                    || sAutor.getText().isEmpty()
                    || tAutor.getText().isEmpty()
                    || aTematica.getText().isEmpty()
                    || genero.getText().isEmpty()
                    || isbn.getText().isEmpty()
                    || listModel.size() <= 0
                );
    }
    
    private void setAllToNull(){
        if(checkColec.isSelected()){
            titulo.setText(null);
            subtitulo.setText(null);
            pAutor.setText(null);
            sAutor.setText(null);
            tAutor.setText(null);
            aTematica.setText(null);
            genero.setText(null);
            isbn.setText(null);
            listModel.removeAllElements();
            nombreColeccion.setText(null);
            isbnColeccion.setText(null);
        }
            titulo.setText(null);
            subtitulo.setText(null);
            pAutor.setText(null);
            sAutor.setText(null);
            tAutor.setText(null);
            aTematica.setText(null);
            genero.setText(null);
            isbn.setText(null);
            listModel.removeAllElements();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<TipoObra> TipoObras;
    private javax.swing.JTextField aTematica;
    private javax.swing.JTextField anio;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cartelATematica;
    private javax.swing.JTextField cartelAnio;
    private javax.swing.JTextField cartelEditorial;
    private javax.swing.JTextField cartelEsColec;
    private javax.swing.JTextField cartelFormato;
    private javax.swing.JTextField cartelGenero;
    private javax.swing.JTextField cartelISBN;
    private javax.swing.JTextField cartelIdioma;
    private javax.swing.JTextField cartelIndice;
    private javax.swing.JTextField cartelIsbnColeccion;
    private javax.swing.JTextField cartelNombre;
    private javax.swing.JTextField cartelPags;
    private javax.swing.JTextField cartelPais;
    private javax.swing.JTextField cartelSubt;
    private javax.swing.JTextField cartelTipoObra;
    private javax.swing.JTextField cartelTitulo;
    private javax.swing.JTextField cartelVol;
    private javax.swing.JTextField cartelpAutor;
    private javax.swing.JTextField cartelsAutor;
    private javax.swing.JTextField carteltAutor;
    private javax.swing.JCheckBox checkColec;
    private javax.swing.JTextField editorial;
    private javax.swing.JComboBox<Formato> formato;
    private javax.swing.JTextField genero;
    private javax.swing.JButton guardarEdicionBtn;
    private javax.swing.JButton guardarObraBtn;
    private javax.swing.JTextField idioma;
    private javax.swing.JTextField indice;
    private javax.swing.JTextField isbn;
    private javax.swing.JTextField isbnColeccion;
    private javax.swing.JList<Edicion> jListEdiciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreColeccion;
    private javax.swing.JTextField pAutor;
    private javax.swing.JTextField pags;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField sAutor;
    private javax.swing.JTextField subtitulo;
    private javax.swing.JTextField tAutor;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JLabel tituloPanel1;
    private javax.swing.JTextField volumenes;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
