/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.GUI;

import com.biblioteca.Biblioteca;
import com.biblioteca.Edicion;
import com.biblioteca.Ejemplar;
import com.biblioteca.Estudiante;
import com.biblioteca.Formato;
import com.biblioteca.Funcionario;
import com.biblioteca.Identificacion;
import com.biblioteca.Lector;
import com.biblioteca.Obra;
import com.biblioteca.TipoDni;
import com.biblioteca.TipoObra;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dalzo
 */
public class RecibirPrestamo extends javax.swing.JFrame {

    ArrayList<Ejemplar> ejemplaresDisponibles = null;
    ArrayList<Obra> obras = null;
    ArrayList<Edicion> ediciones = null;
    ArrayList<Ejemplar> ejemplaresPrestados = null;
    ArrayList<Ejemplar> ejemplaresReservados = null;
    ArrayList<Lector> lectores = null;
    Funcionario funcionario = null;
    
    /**
     * Creates new form RecibirPrestamo
     */
    public RecibirPrestamo() {
        ediciones = Biblioteca.cargarEdiciones();
        obras = Biblioteca.cargarObras(ediciones);
        ejemplaresDisponibles = Biblioteca.cargarEjemplaresDisponibles(obras);
        ejemplaresPrestados = new ArrayList();
        ejemplaresReservados = new ArrayList();
        lectores = Biblioteca.cargarLectores();
        funcionario = Biblioteca.getSesionActual();
        setup();
        initComponents();
        mostrarLectoresConPrestamos(lectores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        cartelCodigo1 = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        tomarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 33, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("TOMAR DEVOLUCION");
        tituloPanel.setFocusable(false);
        jPanel1.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 8, 16));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Ejemplares"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(65, 75, 95));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 450, 290));

        eliminar.setBackground(new java.awt.Color(96, 106, 135));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Volver");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 30));

        buscarBtn.setBackground(new java.awt.Color(96, 106, 135));
        buscarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setText("Buscar");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 100, -1));

        cartelCodigo1.setEditable(false);
        cartelCodigo1.setBackground(new java.awt.Color(3, 33, 67));
        cartelCodigo1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cartelCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        cartelCodigo1.setText("DNI");
        cartelCodigo1.setBorder(null);
        cartelCodigo1.setFocusable(false);
        jPanel1.add(cartelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 20));

        dni.setBackground(new java.awt.Color(0, 8, 16));
        dni.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, -1));

        tomarBtn.setBackground(new java.awt.Color(96, 106, 135));
        tomarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tomarBtn.setForeground(new java.awt.Color(255, 255, 255));
        tomarBtn.setText("Tomar");
        tomarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tomarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tomarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        this.setVisible(false);
        new FuncionarioPanel().setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        ArrayList<Lector> temp = new ArrayList();
        if(dni.getText().isEmpty()){
                mostrarLectoresConPrestamos(lectores);
        }else{
            for (Lector lector : lectores) {
                if(lector.getDni().equals(dni.getText())){
                    temp.add(lector);
                }
            }
            mostrarLectoresConPrestamos(temp);
        }
        
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void tomarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarBtnActionPerformed
        String dniValue = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        
        for(Lector lector : lectores ){
            if(lector.getDni().equals(dniValue)){
                Biblioteca.devolverPrestamo(lector.getPrestamo(), funcionario, ejemplaresPrestados, ejemplaresDisponibles);
            }
        }
        mostrarLectoresConPrestamos(lectores);
    }//GEN-LAST:event_tomarBtnActionPerformed

    private void mostrarLectoresConPrestamos(ArrayList<Lector> lectores){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Lector lector : lectores) {
            if(lector.getPrestamo() != null){
                Object[] row = new Object[3];
                row[0] = lector.getDni();
                row[1] = lector.getNombre();
                row[2] = lector.getPrestamo().getEjemplaresPrestados().size();
                model.addRow(row);
            }
        }
    }
    
    
    //Cargado de objetos en memoria para probar el funcionamiento
    public void setup() {
        //Objetos necesarios para el prestamo
        LocalDate nacimiento = LocalDate.of(2002, 3, 04);
        Lector estudiante = new Estudiante("Jeremias", "Panozzo", "Masculino", nacimiento, "44441299", TipoDni.DNI_TARJETA,
                "jeremiaspanozzo@gmail.com", "3456025247", "Argentino", "Concejal Veiga 1881", 3200, "Concordia",
                "Argentina");
        lectores.add(estudiante);

        Edicion edicion1 = new Edicion("Editorial", "Argentina", 0, 
        2008, 2, 890, "Español", Formato.PAPEL, null);
        ArrayList<Edicion> edicones = new ArrayList<>();
        edicones.add(edicion1);

        Obra obra = new Obra("Titulo", "subtitulo", "autor01", "autor02", 
            "autor03", "Matematica", "Educativo", "9789700502748", edicones, TipoObra.LIBRO);
        edicion1.setObra(obra);

        Identificacion ubi = new Identificacion(null, 1, 1, 1, 1, 1);
        Ejemplar ejemplar1 = new Ejemplar("Observaciones", "9789700502748", 
                LocalDate.of(2008, 4, 21), "Donacion", ubi, obra);
        ubi.setSeUbica(ejemplar1);
        

        Identificacion ubi2 = new Identificacion(null, 1, 1, 1, 1, 2);
        Ejemplar ejemplar2 = new Ejemplar("Observaciones", "9789700502748", 
                LocalDate.of(2008, 4, 21), "Donacion", ubi2, obra);
        ubi2.setSeUbica(ejemplar2);

        ArrayList<Ejemplar> ejemplares = new ArrayList<>();
        ejemplares.add(ejemplar1);
        ejemplares.add(ejemplar2);

        ejemplaresDisponibles.add(ejemplar1);
        ejemplaresDisponibles.add(ejemplar2);

        
        Biblioteca.darPrestamoDomicilio(estudiante,ejemplares,funcionario,5,ejemplaresPrestados,ejemplaresDisponibles, ejemplaresReservados);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecibirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecibirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecibirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecibirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecibirPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField cartelCodigo1;
    private javax.swing.JTextField dni;
    private javax.swing.JButton eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JButton tomarBtn;
    // End of variables declaration//GEN-END:variables
}
